### ISSUE TITLE
登陆报错

### ISSUE THREAD

**Issue by rela0426** [FXLP/MarkTool#15]
您好，无论注册还是登陆，网站均会报错。因为最近一直在尝试用咱们的系统标注数据集，网站打不开所以比较焦虑。报错信息如下：
![error](https://user-images.githubusercontent.com/73818025/203240001-b560b0ea-91ba-41a5-879b-11e600220b6a.png)

**Comment by pjwzg** [comment]
这是自动回复邮件。您好，你所发的邮件已收到。                                                                         联系人：王志刚  联系电话：

**Comment by TaichiLi** [comment]
请问你解决这个问题了吗

**Comment by rela0426** [comment]
> 请问你解决这个问题了吗

目前网站已恢复，你可以试下

**Comment by zhiwenxiong92** [comment]
现在又进不去了。。。Error: Network Error

**Comment by pjwzg** [comment]
这是自动回复邮件。您好，你所发的邮件已收到。                                                                         联系人：王志刚  联系电话：
