### ISSUE TITLE
怎么才能登陆系统呢

### ISSUE THREAD

**Issue by chinaguopeng** [FXLP/MarkTool#3]
我已经下载项目，并初步跑通，但是登陆获取不到 `roles` 注册也不成功 ，提示 `detail: "Not found."`,数据库完全是空的，
没有初始数据，管理后台的账号也没有，请问怎么解决

**Comment by FXLP** [comment]
后台的代码运行了吗

**Comment by FXLP** [comment]
需要运行后台以及更改前端的URL来访问你本地的端口服务

**Comment by chinaguopeng** [comment]
![屏幕截图 2020-10-13 101658](https://user-images.githubusercontent.com/25874614/95807660-495e1200-0d3d-11eb-829f-add72c2002ca.png)
我接口已经访问通了，但是获取不到 `roles` 角色，跳转不到首页
方便加一下微信吗，沟通不太方便 15711330606
数据库基本都是空的，关联关系不清楚，我也没法手动填写

**Comment by FXLP** [comment]
已发送好友申请

**Comment by ericxsun** [comment]
同问

![image](https://user-images.githubusercontent.com/1772912/103075799-546bd300-4607-11eb-9a2f-378fb2067221.png)
