### ISSUE TITLE
MIT 协议也可以申请软件著作权吗

### ISSUE THREAD

**Issue by linonetwo** [FXLP/MarkTool#6]
## Question（提问）

商业应用一般会选择 Apache 2 吧，我写的开源游戏是这么选择的。

还有这个希望能提供一个 ghpages 或者 vercel 预览，大家逛到的时候看起来比较方便。我之前在知识图谱公司也想做这么一套，你做出了我很想做的东西，佩服你。

**Comment by FXLP** [comment]
感谢提醒，后续会进行修改和补充，项目还在不断完善中~
